# Generated by Django 4.2.5 on 2023-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businessloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mobileNum', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('loanAmount', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('emailToken', models.CharField(max_length=220, null=True)),
            ],
        ),
    ]
