# Generated by Django 4.2.5 on 2023-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
