# Generated by Django 4.2.5 on 2023-12-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_queries_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyloan',
            name='mobileNum',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
