# Generated by Django 4.2.5 on 2023-12-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_propertyloan_mobilenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyloan',
            name='mobileNum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
